name: Create and publish nuget package

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'

env:
  DOTNET_VERSION: '6.0.x'
  NUGET_SOURCE: 'https://nuget.pkg.github.com/Senboni/index.json'
  NUGET_SOURCE_NAME: 'github'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        project: [ Sandbox, Sandbox.Toolkit, Sandbox.Toys ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Get version
        id: get_version
        uses: greenygh0st/net-proj-release-version@v1
        with:
          PROJ_FILE: ${{ matrix.project }}/${{ matrix.project }}.csproj

      - name: Next Step
        run: echo "${{ steps.get_version.outputs.RELEASE_VERSION }}"

      - name: Add nuget source
        run: dotnet nuget add source --username Senboni --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name ${{ env.NUGET_SOURCE_NAME }} "${{ env.NUGET_SOURCE }}"

      - name: Install dependencies
        run: dotnet restore

      - name: Build dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Test dotnet
        run: dotnet test --verbosity normal --no-restore

      - name: Pack package
        run: dotnet pack --configuration Release

      - name: Push package
        run: dotnet nuget push "${{ matrix.project }}/bin/Release/${{ matrix.project }}.1.0.1.nupkg" --source "${{ env.NUGET_SOURCE }}"
