name: Build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'

env:
  DOTNET_VERSION: '6.0.x'
  SOURCE_NAME: 'github'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Test dotnet
        run: dotnet test --verbosity normal --no-restore
