name: Create and publish nuget package

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'

env:
  DOTNET_VERSION: '6.0.x'
  NUGET_SOURCE_BASE: 'https://nuget.pkg.github.com/Senboni'
  NUGET_SOURCE_NAME: 'github'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        project: [ Sandbox, Sandbox.Toolkit, Sandbox.Toys ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Add nuget source
        run: dotnet nuget add source --username Senboni --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name ${{ env.NUGET_SOURCE_NAME }} "${{ env.NUGET_SOURCE_BASE }}/index.json"

      - name: Install dependencies
        run: dotnet restore

      - name: Build dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Test dotnet
        run: dotnet test --verbosity normal --no-restore

      - name: Pack package
        run: dotnet pack --configuration Release

      - name: Publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ${{ matrix.project }}/${{ matrix.project }}.csproj
          PACKAGE_NAME: ${{ matrix.project }}
          NUGET_SOURCE: ${{ env.NUGET_SOURCE_BASE }}
          NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}
