name: Build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'

env:
  DOTNET_VERSION: '6.0.x'
  SOURCE_NAME: 'github'
  PROJECT_NAME: [ 'Sandbox', 'Sandbox.Toolkit', 'Sandbox.Toys']

jobs:
  strategy:

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Test dotnet
        run: dotnet test --verbosity normal --no-restore
