name: Create and publish nuget package

on:
  push:
    branches: ['main']
    paths-ignore:
    - 'README.md'

env:
  DOTNET_VERSION: '6.0.x'
  NUGET_SOURCE: 'https://nuget.pkg.github.com/Senboni/index.json'

jobs:
  deploy-packages:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        project: [ Sandbox, Sandbox.Toolkit, Sandbox.Toys ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Get version info
        id: get-version
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        with:
          proj-path: ${{ matrix.project }}/${{ matrix.project }}.csproj

      - name: Add nuget source
        run: dotnet nuget add source --username Senboni --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "${{ env.NUGET_SOURCE }}"

      - name: Install dependencies
        run: dotnet restore "${{ matrix.project }}"

      - name: Build dotnet
        run: dotnet build "${{ matrix.project }}" --configuration Release --no-restore

      - name: Pack package
        run: dotnet pack "${{ matrix.project }}" --configuration Release --no-restore --no-build -p:PackageVersion=${{ steps.get-version.outputs.version }}

      - name: Push package
        run: dotnet nuget push "${{ matrix.project }}/bin/Release/${{ matrix.project }}.${{ steps.get-version.outputs.version }}.nupkg" --source "${{ env.NUGET_SOURCE }}"
